version: '3.9'
services:
  db:
    build: ./database
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-password
    ports:
      - "3306:3306"
    secrets:
      - mysql-root-password
  server:
    build: ./server
    container_name: express_server
    ports:
      - '80:3000'
    environment:
      - PORT=3000

secrets:
  mysql-root-password:
    file: ./database/password.txt

